//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessCCEE.wsListarMed {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/FM")]
    public partial class InvalidParametersFault : BusinessFault {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidParametersFault))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/FM")]
    public abstract partial class BusinessFault : Fault {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnicalFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnexpectedSchemaFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnexpectedTechnicalFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidParametersFault))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/FM")]
    public abstract partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string messageField;
        
        private string uriField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class UnidadeMedida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal valorField;
        
        private bool valorFieldSpecified;
        
        private CodigoUnidadeMedida codigoField;
        
        private bool codigoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
                this.RaisePropertyChanged("valorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CodigoUnidadeMedida codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum CodigoUnidadeMedida {
        
        /// <remarks/>
        KWh,
        
        /// <remarks/>
        MWh,
        
        /// <remarks/>
        MWm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Medida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Periodo periodoField;
        
        private PontoMedicao pontoMedicaoField;
        
        private Medidor medidorField;
        
        private TipoMedicao tipoMedicaoField;
        
        private bool tipoMedicaoFieldSpecified;
        
        private TipoMedida tipoField;
        
        private bool tipoFieldSpecified;
        
        private SubTipoMedida subTipoField;
        
        private bool subTipoFieldSpecified;
        
        private StatusMedida statusField;
        
        private bool statusFieldSpecified;
        
        private double geracaoAtivaField;
        
        private bool geracaoAtivaFieldSpecified;
        
        private double geracaoReativoField;
        
        private bool geracaoReativoFieldSpecified;
        
        private double consumoAtivoField;
        
        private bool consumoAtivoFieldSpecified;
        
        private double consumoReativoField;
        
        private bool consumoReativoFieldSpecified;
        
        private UnidadeMedida unidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PontoMedicao pontoMedicao {
            get {
                return this.pontoMedicaoField;
            }
            set {
                this.pontoMedicaoField = value;
                this.RaisePropertyChanged("pontoMedicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Medidor medidor {
            get {
                return this.medidorField;
            }
            set {
                this.medidorField = value;
                this.RaisePropertyChanged("medidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TipoMedicao tipoMedicao {
            get {
                return this.tipoMedicaoField;
            }
            set {
                this.tipoMedicaoField = value;
                this.RaisePropertyChanged("tipoMedicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMedicaoSpecified {
            get {
                return this.tipoMedicaoFieldSpecified;
            }
            set {
                this.tipoMedicaoFieldSpecified = value;
                this.RaisePropertyChanged("tipoMedicaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TipoMedida tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public SubTipoMedida subTipo {
            get {
                return this.subTipoField;
            }
            set {
                this.subTipoField = value;
                this.RaisePropertyChanged("subTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subTipoSpecified {
            get {
                return this.subTipoFieldSpecified;
            }
            set {
                this.subTipoFieldSpecified = value;
                this.RaisePropertyChanged("subTipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public StatusMedida status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double geracaoAtiva {
            get {
                return this.geracaoAtivaField;
            }
            set {
                this.geracaoAtivaField = value;
                this.RaisePropertyChanged("geracaoAtiva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geracaoAtivaSpecified {
            get {
                return this.geracaoAtivaFieldSpecified;
            }
            set {
                this.geracaoAtivaFieldSpecified = value;
                this.RaisePropertyChanged("geracaoAtivaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double geracaoReativo {
            get {
                return this.geracaoReativoField;
            }
            set {
                this.geracaoReativoField = value;
                this.RaisePropertyChanged("geracaoReativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geracaoReativoSpecified {
            get {
                return this.geracaoReativoFieldSpecified;
            }
            set {
                this.geracaoReativoFieldSpecified = value;
                this.RaisePropertyChanged("geracaoReativoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double consumoAtivo {
            get {
                return this.consumoAtivoField;
            }
            set {
                this.consumoAtivoField = value;
                this.RaisePropertyChanged("consumoAtivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consumoAtivoSpecified {
            get {
                return this.consumoAtivoFieldSpecified;
            }
            set {
                this.consumoAtivoFieldSpecified = value;
                this.RaisePropertyChanged("consumoAtivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double consumoReativo {
            get {
                return this.consumoReativoField;
            }
            set {
                this.consumoReativoField = value;
                this.RaisePropertyChanged("consumoReativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consumoReativoSpecified {
            get {
                return this.consumoReativoFieldSpecified;
            }
            set {
                this.consumoReativoFieldSpecified = value;
                this.RaisePropertyChanged("consumoReativoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public UnidadeMedida unidade {
            get {
                return this.unidadeField;
            }
            set {
                this.unidadeField = value;
                this.RaisePropertyChanged("unidade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Periodo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descricaoField;
        
        private System.DateTime inicioField;
        
        private bool inicioFieldSpecified;
        
        private System.DateTime fimField;
        
        private bool fimFieldSpecified;
        
        private string nomeField;
        
        private int numeroField;
        
        private bool numeroFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inicioSpecified {
            get {
                return this.inicioFieldSpecified;
            }
            set {
                this.inicioFieldSpecified = value;
                this.RaisePropertyChanged("inicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime fim {
            get {
                return this.fimField;
            }
            set {
                this.fimField = value;
                this.RaisePropertyChanged("fim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fimSpecified {
            get {
                return this.fimFieldSpecified;
            }
            set {
                this.fimFieldSpecified = value;
                this.RaisePropertyChanged("fimSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
                this.RaisePropertyChanged("numeroSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class PontoMedicao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private int chaveField;
        
        private bool chaveFieldSpecified;
        
        private string nomeField;
        
        private AgenteRelacionado[] agentesRelacionadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
                this.RaisePropertyChanged("chave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chaveSpecified {
            get {
                return this.chaveFieldSpecified;
            }
            set {
                this.chaveFieldSpecified = value;
                this.RaisePropertyChanged("chaveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("agenteRelacionado", IsNullable=false)]
        public AgenteRelacionado[] agentesRelacionados {
            get {
                return this.agentesRelacionadosField;
            }
            set {
                this.agentesRelacionadosField = value;
                this.RaisePropertyChanged("agentesRelacionados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class AgenteRelacionado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Agente agenteField;
        
        private TipoAgentePonto tipoRelacaoField;
        
        private bool tipoRelacaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Agente agente {
            get {
                return this.agenteField;
            }
            set {
                this.agenteField = value;
                this.RaisePropertyChanged("agente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoAgentePonto tipoRelacao {
            get {
                return this.tipoRelacaoField;
            }
            set {
                this.tipoRelacaoField = value;
                this.RaisePropertyChanged("tipoRelacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoRelacaoSpecified {
            get {
                return this.tipoRelacaoFieldSpecified;
            }
            set {
                this.tipoRelacaoFieldSpecified = value;
                this.RaisePropertyChanged("tipoRelacaoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Agente : Organizacao {
        
        private Categoria categoriaField;
        
        private Classe classeField;
        
        private Agente representanteField;
        
        private bool habilitaRepresentacaoField;
        
        private bool habilitaRepresentacaoFieldSpecified;
        
        private Periodo vigenciaField;
        
        private Periodo operacaoField;
        
        private Agente[] perfisField;
        
        private bool comercializadorVarejistaField;
        
        private bool comercializadorVarejistaFieldSpecified;
        
        private bool perfilPrincipalField;
        
        private bool perfilPrincipalFieldSpecified;
        
        private ContaBancaria[] dadosBancariosField;
        
        private FonteEnergia fonteEnergiaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Categoria categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Classe classe {
            get {
                return this.classeField;
            }
            set {
                this.classeField = value;
                this.RaisePropertyChanged("classe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Agente representante {
            get {
                return this.representanteField;
            }
            set {
                this.representanteField = value;
                this.RaisePropertyChanged("representante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool habilitaRepresentacao {
            get {
                return this.habilitaRepresentacaoField;
            }
            set {
                this.habilitaRepresentacaoField = value;
                this.RaisePropertyChanged("habilitaRepresentacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool habilitaRepresentacaoSpecified {
            get {
                return this.habilitaRepresentacaoFieldSpecified;
            }
            set {
                this.habilitaRepresentacaoFieldSpecified = value;
                this.RaisePropertyChanged("habilitaRepresentacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Periodo vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Periodo operacao {
            get {
                return this.operacaoField;
            }
            set {
                this.operacaoField = value;
                this.RaisePropertyChanged("operacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("perfilAgente", IsNullable=false)]
        public Agente[] perfis {
            get {
                return this.perfisField;
            }
            set {
                this.perfisField = value;
                this.RaisePropertyChanged("perfis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool comercializadorVarejista {
            get {
                return this.comercializadorVarejistaField;
            }
            set {
                this.comercializadorVarejistaField = value;
                this.RaisePropertyChanged("comercializadorVarejista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comercializadorVarejistaSpecified {
            get {
                return this.comercializadorVarejistaFieldSpecified;
            }
            set {
                this.comercializadorVarejistaFieldSpecified = value;
                this.RaisePropertyChanged("comercializadorVarejistaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool perfilPrincipal {
            get {
                return this.perfilPrincipalField;
            }
            set {
                this.perfilPrincipalField = value;
                this.RaisePropertyChanged("perfilPrincipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perfilPrincipalSpecified {
            get {
                return this.perfilPrincipalFieldSpecified;
            }
            set {
                this.perfilPrincipalFieldSpecified = value;
                this.RaisePropertyChanged("perfilPrincipalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contaBancaria", IsNullable=false)]
        public ContaBancaria[] dadosBancarios {
            get {
                return this.dadosBancariosField;
            }
            set {
                this.dadosBancariosField = value;
                this.RaisePropertyChanged("dadosBancarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public FonteEnergia fonteEnergia {
            get {
                return this.fonteEnergiaField;
            }
            set {
                this.fonteEnergiaField = value;
                this.RaisePropertyChanged("fonteEnergia");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Categoria : Dominio {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Categoria))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Classe))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoLogradouro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoEndereco))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public abstract partial class Dominio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Classe : Dominio {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class TipoLogradouro : Dominio {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class TipoEndereco : Dominio {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class ContaBancaria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string digitoVerificadorField;
        
        private string tipoField;
        
        private Agencia agenciaField;
        
        private string descricaoContaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string digitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
                this.RaisePropertyChanged("digitoVerificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Agencia agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
                this.RaisePropertyChanged("agencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descricaoConta {
            get {
                return this.descricaoContaField;
            }
            set {
                this.descricaoContaField = value;
                this.RaisePropertyChanged("descricaoConta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Agencia : Organizacao {
        
        private string numeroField;
        
        private string digitoVerificadorField;
        
        private Banco bancoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string digitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
                this.RaisePropertyChanged("digitoVerificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Banco banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
                this.RaisePropertyChanged("banco");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Banco : Organizacao {
        
        private int numeroField;
        
        private bool numeroFieldSpecified;
        
        private bool assinaturaEletronicaField;
        
        private bool assinaturaEletronicaFieldSpecified;
        
        private Periodo dataAdesaoAssinaturaBiometricaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
                this.RaisePropertyChanged("numeroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool assinaturaEletronica {
            get {
                return this.assinaturaEletronicaField;
            }
            set {
                this.assinaturaEletronicaField = value;
                this.RaisePropertyChanged("assinaturaEletronica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assinaturaEletronicaSpecified {
            get {
                return this.assinaturaEletronicaFieldSpecified;
            }
            set {
                this.assinaturaEletronicaFieldSpecified = value;
                this.RaisePropertyChanged("assinaturaEletronicaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Periodo dataAdesaoAssinaturaBiometrica {
            get {
                return this.dataAdesaoAssinaturaBiometricaField;
            }
            set {
                this.dataAdesaoAssinaturaBiometricaField = value;
                this.RaisePropertyChanged("dataAdesaoAssinaturaBiometrica");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Agente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Banco))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Agencia))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Organizacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string razaoSocialField;
        
        private string siglaField;
        
        private string cnpjField;
        
        private string segmentoMercadoField;
        
        private TipoOrganizacao tipoField;
        
        private bool tipoFieldSpecified;
        
        private StatusOrganizacao statusField;
        
        private bool statusFieldSpecified;
        
        private string siteField;
        
        private EnderecoPostal[] enderecosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string razaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
                this.RaisePropertyChanged("razaoSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
                this.RaisePropertyChanged("sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string segmentoMercado {
            get {
                return this.segmentoMercadoField;
            }
            set {
                this.segmentoMercadoField = value;
                this.RaisePropertyChanged("segmentoMercado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TipoOrganizacao tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public StatusOrganizacao status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
                this.RaisePropertyChanged("site");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("endereco", IsNullable=false)]
        public EnderecoPostal[] enderecos {
            get {
                return this.enderecosField;
            }
            set {
                this.enderecosField = value;
                this.RaisePropertyChanged("enderecos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum TipoOrganizacao {
        
        /// <remarks/>
        AGENTE,
        
        /// <remarks/>
        NAO_AGENTE,
        
        /// <remarks/>
        PARTICIPANTE_SCDE,
        
        /// <remarks/>
        REPRESENTADO,
        
        /// <remarks/>
        PERFIL_AGENTE,
        
        /// <remarks/>
        PERFIL_AGENTE_PRINCIPAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum StatusOrganizacao {
        
        /// <remarks/>
        ADERIDO,
        
        /// <remarks/>
        ATIVADO,
        
        /// <remarks/>
        DESATIVADO,
        
        /// <remarks/>
        DESLIGADO,
        
        /// <remarks/>
        EM_ADESAO,
        
        /// <remarks/>
        OUTROS,
        
        /// <remarks/>
        PROCESSO_ADESAO_CANCELADO,
        
        /// <remarks/>
        SUSPENSO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class EnderecoPostal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private TipoEndereco tipoField;
        
        private string codigoEnderecamentoPostalField;
        
        private TipoLogradouro tipoLogradouroField;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        private TipoFronteiraGeografica paisField;
        
        private TipoFronteiraGeografica estadoField;
        
        private TipoFronteiraGeografica cidadeField;
        
        private TipoFronteiraGeografica bairroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoEndereco tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoEnderecamentoPostal {
            get {
                return this.codigoEnderecamentoPostalField;
            }
            set {
                this.codigoEnderecamentoPostalField = value;
                this.RaisePropertyChanged("codigoEnderecamentoPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TipoLogradouro tipoLogradouro {
            get {
                return this.tipoLogradouroField;
            }
            set {
                this.tipoLogradouroField = value;
                this.RaisePropertyChanged("tipoLogradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TipoFronteiraGeografica pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public TipoFronteiraGeografica estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public TipoFronteiraGeografica cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public TipoFronteiraGeografica bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("bairro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class TipoFronteiraGeografica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private TipoFronteiraGeograficaEnum tipoField;
        
        private bool tipoFieldSpecified;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoFronteiraGeograficaEnum tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum TipoFronteiraGeograficaEnum {
        
        /// <remarks/>
        PAIS,
        
        /// <remarks/>
        SUBMERCADO,
        
        /// <remarks/>
        ESTADO,
        
        /// <remarks/>
        CIDADE,
        
        /// <remarks/>
        BAIRRO,
        
        /// <remarks/>
        CODIGO_POSTAL,
        
        /// <remarks/>
        ENDERECO,
        
        /// <remarks/>
        RUA,
        
        /// <remarks/>
        NUMERO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class FonteEnergia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string nomeField;
        
        private string descricaoField;
        
        private string siglaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
                this.RaisePropertyChanged("sigla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum TipoAgentePonto {
        
        /// <remarks/>
        AGENTE_MEDICAO,
        
        /// <remarks/>
        AGENTE_CONECTANTE,
        
        /// <remarks/>
        AGENTE_CONECTADO,
        
        /// <remarks/>
        AGENTE_PENALIDADE,
        
        /// <remarks/>
        AGENTE_CONTRATO_USO_FIO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public partial class Medidor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum TipoMedicao {
        
        /// <remarks/>
        COLETA,
        
        /// <remarks/>
        INSPECAO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum TipoMedida {
        
        /// <remarks/>
        FALTANTES,
        
        /// <remarks/>
        CONSOLIDADA,
        
        /// <remarks/>
        FINAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum SubTipoMedida {
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        L,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum StatusMedida {
        
        /// <remarks/>
        HCC,
        
        /// <remarks/>
        HCI,
        
        /// <remarks/>
        HEC,
        
        /// <remarks/>
        HEI,
        
        /// <remarks/>
        HIF,
        
        /// <remarks/>
        HE,
        
        /// <remarks/>
        HEE,
        
        /// <remarks/>
        HEA,
        
        /// <remarks/>
        HR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BM/v1")]
    public partial class ListarMedidaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Medida[] medidasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("medida", IsNullable=false)]
        public Medida[] medidas {
            get {
                return this.medidasField;
            }
            set {
                this.medidasField = value;
                this.RaisePropertyChanged("medidas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BM/v1")]
    public partial class ListarMedidaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TipoRelacionamentoAgentePontoMedicao relacionamentoAgentePontoField;
        
        private bool relacionamentoAgentePontoFieldSpecified;
        
        private PontoMedicao pontoMedicaoField;
        
        private Medidor medidorField;
        
        private TipoMedida tipoMedidaField;
        
        private bool tipoMedidaFieldSpecified;
        
        private TipoMedicao tipoMedicaoField;
        
        private bool tipoMedicaoFieldSpecified;
        
        private StatusMedida statusMedidaField;
        
        private bool statusMedidaFieldSpecified;
        
        private Periodo periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TipoRelacionamentoAgentePontoMedicao relacionamentoAgentePonto {
            get {
                return this.relacionamentoAgentePontoField;
            }
            set {
                this.relacionamentoAgentePontoField = value;
                this.RaisePropertyChanged("relacionamentoAgentePonto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool relacionamentoAgentePontoSpecified {
            get {
                return this.relacionamentoAgentePontoFieldSpecified;
            }
            set {
                this.relacionamentoAgentePontoFieldSpecified = value;
                this.RaisePropertyChanged("relacionamentoAgentePontoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PontoMedicao pontoMedicao {
            get {
                return this.pontoMedicaoField;
            }
            set {
                this.pontoMedicaoField = value;
                this.RaisePropertyChanged("pontoMedicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Medidor medidor {
            get {
                return this.medidorField;
            }
            set {
                this.medidorField = value;
                this.RaisePropertyChanged("medidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TipoMedida tipoMedida {
            get {
                return this.tipoMedidaField;
            }
            set {
                this.tipoMedidaField = value;
                this.RaisePropertyChanged("tipoMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMedidaSpecified {
            get {
                return this.tipoMedidaFieldSpecified;
            }
            set {
                this.tipoMedidaFieldSpecified = value;
                this.RaisePropertyChanged("tipoMedidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TipoMedicao tipoMedicao {
            get {
                return this.tipoMedicaoField;
            }
            set {
                this.tipoMedicaoField = value;
                this.RaisePropertyChanged("tipoMedicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMedicaoSpecified {
            get {
                return this.tipoMedicaoFieldSpecified;
            }
            set {
                this.tipoMedicaoFieldSpecified = value;
                this.RaisePropertyChanged("tipoMedicaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public StatusMedida statusMedida {
            get {
                return this.statusMedidaField;
            }
            set {
                this.statusMedidaField = value;
                this.RaisePropertyChanged("statusMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusMedidaSpecified {
            get {
                return this.statusMedidaFieldSpecified;
            }
            set {
                this.statusMedidaFieldSpecified = value;
                this.RaisePropertyChanged("statusMedidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Periodo periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/BO/v1")]
    public enum TipoRelacionamentoAgentePontoMedicao {
        
        /// <remarks/>
        MEDICAO,
        
        /// <remarks/>
        CONECTANTE,
        
        /// <remarks/>
        CONECTADO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnexpectedSchemaFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnexpectedTechnicalFault))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/FM")]
    public abstract partial class TechnicalFault : Fault {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/FM")]
    public partial class UnexpectedSchemaFault : TechnicalFault {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/FM")]
    public partial class UnexpectedTechnicalFault : TechnicalFault {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.energia.org.br/BS/v1", ConfigurationName="wsListarMed.ListarMedidaBSv1PortType")]
    public interface ListarMedidaBSv1PortType {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação listarMedida não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="listarMedida", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccessCCEE.wsListarMed.InvalidParametersFault), Action="listarMedida", Name="invalidParametersFault", Namespace="http://xmlns.energia.org.br/FM")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccessCCEE.wsListarMed.UnexpectedTechnicalFault), Action="listarMedida", Name="unexpectedTechnicalFault", Namespace="http://xmlns.energia.org.br/FM")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccessCCEE.wsListarMed.UnexpectedSchemaFault), Action="listarMedida", Name="unexpectedSchemaFault", Namespace="http://xmlns.energia.org.br/FM")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Fault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dominio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Organizacao))]
        AccessCCEE.wsListarMed.listarMedidaResponse1 listarMedida(AccessCCEE.wsListarMed.listarMedidaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="listarMedida", ReplyAction="*")]
        System.Threading.Tasks.Task<AccessCCEE.wsListarMed.listarMedidaResponse1> listarMedidaAsync(AccessCCEE.wsListarMed.listarMedidaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class SecurityHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UsernameTokenType usernameTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UsernameTokenType UsernameToken {
            get {
                return this.usernameTokenField;
            }
            set {
                this.usernameTokenField = value;
                this.RaisePropertyChanged("UsernameToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class UsernameTokenType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.energia.org.br/MH/v1")]
    public partial class MessageHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoPerfilAgenteField;
        
        private string transactionIdField;
        
        private string[] listaCodigoPerfilAgenteField;
        
        private string versaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codigoPerfilAgente {
            get {
                return this.codigoPerfilAgenteField;
            }
            set {
                this.codigoPerfilAgenteField = value;
                this.RaisePropertyChanged("codigoPerfilAgente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("codigoPerfilAgente", IsNullable=false)]
        public string[] listaCodigoPerfilAgente {
            get {
                return this.listaCodigoPerfilAgenteField;
            }
            set {
                this.listaCodigoPerfilAgenteField = value;
                this.RaisePropertyChanged("listaCodigoPerfilAgente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
                this.RaisePropertyChanged("versao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarMedidaRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public AccessCCEE.wsListarMed.SecurityHeaderType Security;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://xmlns.energia.org.br/MH/v1")]
        public AccessCCEE.wsListarMed.MessageHeaderType messageHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.energia.org.br/BM/v1", Order=0)]
        public AccessCCEE.wsListarMed.ListarMedidaRequest listarMedida;
        
        public listarMedidaRequest1() {
        }
        
        public listarMedidaRequest1(AccessCCEE.wsListarMed.SecurityHeaderType Security, AccessCCEE.wsListarMed.MessageHeaderType messageHeader, AccessCCEE.wsListarMed.ListarMedidaRequest listarMedida) {
            this.Security = Security;
            this.messageHeader = messageHeader;
            this.listarMedida = listarMedida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarMedidaResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://xmlns.energia.org.br/MH/v1")]
        public AccessCCEE.wsListarMed.MessageHeaderType messageHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.energia.org.br/BM/v1", Order=0)]
        public AccessCCEE.wsListarMed.ListarMedidaResponse listarMedidaResponse;
        
        public listarMedidaResponse1() {
        }
        
        public listarMedidaResponse1(AccessCCEE.wsListarMed.MessageHeaderType messageHeader, AccessCCEE.wsListarMed.ListarMedidaResponse listarMedidaResponse) {
            this.messageHeader = messageHeader;
            this.listarMedidaResponse = listarMedidaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListarMedidaBSv1PortTypeChannel : AccessCCEE.wsListarMed.ListarMedidaBSv1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarMedidaBSv1PortTypeClient : System.ServiceModel.ClientBase<AccessCCEE.wsListarMed.ListarMedidaBSv1PortType>, AccessCCEE.wsListarMed.ListarMedidaBSv1PortType {
        
        public ListarMedidaBSv1PortTypeClient() {
        }
        
        public ListarMedidaBSv1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListarMedidaBSv1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarMedidaBSv1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarMedidaBSv1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccessCCEE.wsListarMed.listarMedidaResponse1 AccessCCEE.wsListarMed.ListarMedidaBSv1PortType.listarMedida(AccessCCEE.wsListarMed.listarMedidaRequest1 request) {
            return base.Channel.listarMedida(request);
        }
        
        public AccessCCEE.wsListarMed.ListarMedidaResponse listarMedida(AccessCCEE.wsListarMed.SecurityHeaderType Security, ref AccessCCEE.wsListarMed.MessageHeaderType messageHeader, AccessCCEE.wsListarMed.ListarMedidaRequest listarMedida1) {
            AccessCCEE.wsListarMed.listarMedidaRequest1 inValue = new AccessCCEE.wsListarMed.listarMedidaRequest1();
            inValue.Security = Security;
            inValue.messageHeader = messageHeader;
            inValue.listarMedida = listarMedida1;
            AccessCCEE.wsListarMed.listarMedidaResponse1 retVal = ((AccessCCEE.wsListarMed.ListarMedidaBSv1PortType)(this)).listarMedida(inValue);
            messageHeader = retVal.messageHeader;
            return retVal.listarMedidaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccessCCEE.wsListarMed.listarMedidaResponse1> AccessCCEE.wsListarMed.ListarMedidaBSv1PortType.listarMedidaAsync(AccessCCEE.wsListarMed.listarMedidaRequest1 request) {
            return base.Channel.listarMedidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccessCCEE.wsListarMed.listarMedidaResponse1> listarMedidaAsync(AccessCCEE.wsListarMed.SecurityHeaderType Security, AccessCCEE.wsListarMed.MessageHeaderType messageHeader, AccessCCEE.wsListarMed.ListarMedidaRequest listarMedida) {
            AccessCCEE.wsListarMed.listarMedidaRequest1 inValue = new AccessCCEE.wsListarMed.listarMedidaRequest1();
            inValue.Security = Security;
            inValue.messageHeader = messageHeader;
            inValue.listarMedida = listarMedida;
            return ((AccessCCEE.wsListarMed.ListarMedidaBSv1PortType)(this)).listarMedidaAsync(inValue);
        }
    }
}
